# #
# #print("Phyton ile ilk günüm!")
# #print("Fonksiyon şu şekilde tanımlanır: print('ekrana yazdırılacak yazı')")
# #print("Merhaba Dünya\nMerhaba Dünya\nMerhaba Dünya\n")
# #print("Merhaba Dünya")
# #print("Merhaba Dünya")
# #print("Merhaba Dünya")
# #print("Merhaba"+" "+"Şahin!")
# #print(input("merhaba, adın nedir?"))
# #print("Merhaba " + input("Merhaba,Adın Nedir?") + "!")
# #print(len(input("merhaba , adın nedir ?")))
# #input("merhaba adın nedir")
# #print("memnun oldun ben de ahmet")
# #print("şahin")
# #print("tasin")
# #print(len(input("Merhaba, Adın Nedir?")))
# #input("Merhaba, Adın Nedir?")
# #len("toprak")
# #print(6)
# #input("7")
# #input("2")
# #print("7^"+"7")
# #print("2"+"2")
# #String
# # print(len(str(1234567890)))
# # print("merhaba"[3])
# # #Integer
# # print(123 + 456)
# # print(123_456_789)
# # #Float
# # print(3.12345)
# # #Boolean
# # print(True)
# # print(False)
# # len(input("merhaba , adın ne?"))
# # str(IsimUzunluk)
# # print("Isminde"+ IsimUzunluk)
# # str(input("22"))
# # int(42[0]) + int(32[1])
# # print("toplam " + str(toplam))
# # print(2 * 4 + 6 / 3 - 2)
# boy = float(input("boyunuzu girin (m): "))
